### ISSUE TITLE
Hide join/part message for haumbotox

### ISSUE THREAD

**Issue by gagath** [haum/vushaum#3]
In order to reduce noise on the channel, we can send IRC messages without actually joining the channel by [imitating the Github IRC hook](https://github.com/github/github-services/blob/master/docs/irc#L72).

This makes the bot harder to debug, but if we trust the code then it could be worth.

**Comment by sebvallee** [comment]
But the bot needs the voice status to send commands to Com`Bot, and I think it gets this status only by joining the channel...

**Comment by gagath** [comment]
I forgot about that. Closing then.

**Comment by sebvallee** [comment]
But maybe we can make Com`Bot and haumbotox interacts with eachothers in private message ?

**Comment by rebrec** [comment]
Or maybe it is time to make One bot to rule them all ? In other words, One bot idling on the channel exposing differents services to other scripts (one of them could be to be triggered via IRC commands after receiving an identification private message)

**Comment by neomilium** [comment]
It is really a problem to have noise on IRC ?

2015-12-29 12:21 GMT+01:00 Sébastien Vallée notifications@github.com:

> But maybe we can make Com`Bot and haumbotox interacts with eachothers in
> private message ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/haum/vushaum/issues/3#issuecomment-167768018.

## 

Romuald

**Comment by fredblain** [comment]
The Github web-service for IRC has the "Message without join" option, reason why we can't read any join/part/other message when an issue is opened/closed/updated on the channel. It would be then interesting to check how they implemented it.

**Comment by rebrec** [comment]
The implementation is simple fred : you just need to enable msg outside of the channel by setting it -n i think.
If you do so, anyone can send msg to the chan from outside the chan ...

**Comment by fredblain** [comment]
@rebrec : this is what we're using with the GitHub web-hooks as I mentioned above. So, if it's already enabled according to what you said, we could use it for our bots.

**Comment by rebrec** [comment]
you are right fredblain, the only problem is that from now Combot only accept commands from voiced nicknames in the channel
